-- 1) Create enum type
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'AuditEventType') THEN
    CREATE TYPE "AuditEventType" AS ENUM (
      'SESSION_OPENED',
      'SESSION_PHASE_CHANGED',
      'SYSTEM_STATE_CHANGED',
      'USER_CONTEXT_CREATED',
      'USER_CONTEXT_RESET',
      'USER_CONTEXT_LAST_SESSION_SET',
      'USER_CONTEXT_MODELSET_ACTIVATED',
      'USER_CONTEXT_MODELSET_CLEARED',
      'IDENTITY_VERSION_CREATED',
      'CONFIDENCE_RECORDED',
      'PRESSURE_RECORDED',
      'TRANSITION_BLOCKED',
      'MUTATION_BLOCKED'
    );
  END IF;
END $$;

-- 2) Add a new enum-typed column (nullable for now)
ALTER TABLE "AuditEvent"
ADD COLUMN IF NOT EXISTS "eventType_new" "AuditEventType";

-- 3) Copy data over with a safe mapping.
--    Anything unknown becomes MUTATION_BLOCKED (structural “catch-all”).
UPDATE "AuditEvent"
SET "eventType_new" = CASE "eventType"
  WHEN 'SESSION_OPENED' THEN 'SESSION_OPENED'::"AuditEventType"

  WHEN 'USER_CONTEXT_CREATED' THEN 'USER_CONTEXT_CREATED'::"AuditEventType"
  WHEN 'USER_CONTEXT_RESET' THEN 'USER_CONTEXT_RESET'::"AuditEventType"
  WHEN 'USER_CONTEXT_LAST_SESSION_SET' THEN 'USER_CONTEXT_LAST_SESSION_SET'::"AuditEventType"
  WHEN 'USER_CONTEXT_MODELSET_ACTIVATED' THEN 'USER_CONTEXT_MODELSET_ACTIVATED'::"AuditEventType"
  WHEN 'USER_CONTEXT_MODELSET_CLEARED' THEN 'USER_CONTEXT_MODELSET_CLEARED'::"AuditEventType"

  WHEN 'IDENTITY_VERSION_CREATED' THEN 'IDENTITY_VERSION_CREATED'::"AuditEventType"
  WHEN 'CONFIDENCE_RECORDED' THEN 'CONFIDENCE_RECORDED'::"AuditEventType"
  WHEN 'PRESSURE_RECORDED' THEN 'PRESSURE_RECORDED'::"AuditEventType"

  WHEN 'USER_CONTEXT_MUTATION_BLOCKED' THEN 'MUTATION_BLOCKED'::"AuditEventType"
  WHEN 'IDENTITY_VERSION_MUTATION_BLOCKED' THEN 'MUTATION_BLOCKED'::"AuditEventType"
  WHEN 'CONFIDENCE_MUTATION_BLOCKED' THEN 'MUTATION_BLOCKED'::"AuditEventType"
  WHEN 'PRESSURE_MUTATION_BLOCKED' THEN 'MUTATION_BLOCKED'::"AuditEventType"

  ELSE 'MUTATION_BLOCKED'::"AuditEventType"
END
WHERE "eventType_new" IS NULL;

-- 4) Enforce NOT NULL on the new column
ALTER TABLE "AuditEvent"
ALTER COLUMN "eventType_new" SET NOT NULL;

-- 5) Drop old column and rename new column
ALTER TABLE "AuditEvent" DROP COLUMN "eventType";
ALTER TABLE "AuditEvent" RENAME COLUMN "eventType_new" TO "eventType";
